export const publicationOrder = {
  preprints: [
    "do-reasoning-vlms-inversely-scale.mts",
    "hyperclova_omni.mts",
  ],
  "2026": [
    "mira.mts",
    "oaof.mts",
    "specetd.mts",
    "lipo.mts",
    "auditorybench-plus-plus.mts",
    "iterquant.mts",
    "linkd.mts",
    "smallforsmall.mts",
    "post-training-quantization-of-vision-encoders-needs-prefixing-registers.mts",
    "neural-weight-compression-for-language-models.mts",
  ],
  "2025": [
    "s2cap.mts",
    "imagine-to-hear.mts",
    "prompt-based-depth-pruning.mts",
    "towards-federated-low-rank-adaptation.mts",
    "fast-training-of-sinusoidal-neural-fields.mts",
    "zip-zeroth-order-prompt-tuning.mts",
    "audiobert.mts",
    "communication-efficient-split-learning.mts",
    "internal-representations-of-graph-metanetworks.mts",
  ],
  "2024": [
    "limited-teacher-supervision.mts",
    "prefixing-attention-sinks.mts",
    "rethinking-pruning-llms.mts",
    "role-of-masking-for-efficient-skd.mts",
    "neural-image-compression-with-text-guided-encoding.mts",
    "hybrid-neural-representations-for-spherical-data.mts",
    "data-transformation-accelerates-neural-field-training.mts",
    "discovering-and-mitigating-visual-biases.mts",
    "scanner-unseen-entities.mts",
    "few-shot-unlearning.mts",
    "attention-aware-semantic-communications.mts",
  ],
  "2023": [
    "context-pruned-meta-learning.mts",
    "modality-agnostic-variational-compression.mts",
    "breaking-the-spurious-causality.mts",
    "semi-ensemble.mts",
    "sharpness-aware-minimization-large-mini-batches.mts",
    "debiased-distillation-by-transplanting-the-last-layer.mts",
  ],
  "2022": [
    "scalable-neural-video-representations.mts",
    "meta-learning-with-self-improving-momentum-targets.mts",
    "spread-spurious-attribute.mts",
    "zero-shot-blind-image-denoising.mts",
  ],
  "2021": [
    "meta-learning-sparse-implicit-neural-representations.mts",
    "co2l.mts",
    "provable-memorization.mts",
    "minimum-width-universal-approximation.mts",
    "layer-adaptive-sparsity.mts",
    "masker.mts",
    "greedyprune.mts",
  ],
  "2020": [
    "learning-bounds-for-risk-sensitive-learning.mts",
    "learning-from-failure.mts",
    "lookahead.mts",
  ],
  "pre-2020": [
    "finite-dimensional-coding-schemes.mts",
    "minimax-statistical-learning-wasserstein.mts",
    "mmse-estimation-quantized-observations.mts",
  ],
  "domestic-posters": [
    "bias-of-generative-image-compression.mts",
    "sparse-identification-model-biased.mts",
  ],
} as const;
