export const publicationOrder = {
  preprints: [
    "over-alignment-vs-over-fitting.paper.mts",
    "lost-in-the-prompt-order.paper.mts",
    "do-reasoning-vlms-inversely-scale.paper.mts",
    "neural-weight-compression-for-language-models.paper.mts",
    "post-training-quantization-of-vision-encoders-needs-prefixing-registers.paper.mts",
    "speculative-end-turn-detector.paper.mts",
  ],
  "2026": ["auditorybench-plus-plus.paper.mts", "iterquant.paper.mts"],
  "2025": [
    "s2cap.paper.mts",
    "imagine-to-hear.paper.mts",
    "prompt-based-depth-pruning.paper.mts",
    "towards-federated-low-rank-adaptation.paper.mts",
    "fast-training-of-sinusoidal-neural-fields.paper.mts",
    "zip-zeroth-order-prompt-tuning.paper.mts",
    "audiobert.paper.mts",
    "communication-efficient-split-learning.paper.mts",
    "internal-representations-of-graph-metanetworks.paper.mts",
  ],
  "2024": [
    "limited-teacher-supervision.paper.mts",
    "prefixing-attention-sinks.paper.mts",
    "rethinking-pruning-llms.paper.mts",
    "role-of-masking-for-efficient-skd.paper.mts",
    "neural-image-compression-with-text-guided-encoding.paper.mts",
    "hybrid-neural-representations-for-spherical-data.paper.mts",
    "data-transformation-accelerates-neural-field-training.paper.mts",
    "discovering-and-mitigating-visual-biases.paper.mts",
    "scanner-unseen-entities.paper.mts",
    "few-shot-unlearning.paper.mts",
    "attention-aware-semantic-communications.paper.mts",
  ],
  "2023": [
    "context-pruned-meta-learning.paper.mts",
    "modality-agnostic-variational-compression.paper.mts",
    "breaking-the-spurious-causality.paper.mts",
    "semi-ensemble.paper.mts",
    "sharpness-aware-minimization-large-mini-batches.paper.mts",
    "debiased-distillation-by-transplanting-the-last-layer.paper.mts",
  ],
  "2022": [
    "scalable-neural-video-representations.paper.mts",
    "meta-learning-with-self-improving-momentum-targets.paper.mts",
    "spread-spurious-attribute.paper.mts",
    "zero-shot-blind-image-denoising.paper.mts",
  ],
  "2021": [
    "meta-learning-sparse-implicit-neural-representations.paper.mts",
    "co2l.paper.mts",
    "provable-memorization.paper.mts",
    "minimum-width-universal-approximation.paper.mts",
    "layer-adaptive-sparsity.paper.mts",
    "masker.paper.mts",
    "greedyprune.paper.mts",
  ],
  "2020": [
    "learning-bounds-for-risk-sensitive-learning.paper.mts",
    "learning-from-failure.paper.mts",
    "lookahead.paper.mts",
  ],
  "pre-2020": [
    "finite-dimensional-coding-schemes.paper.mts",
    "minimax-statistical-learning-wasserstein.paper.mts",
    "mmse-estimation-quantized-observations.paper.mts",
  ],
  "domestic-posters": [
    "bias-of-generative-image-compression.paper.mts",
    "sparse-identification-model-biased.paper.mts",
  ],
} as const;
